apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: app
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /microbot
        backend:
          serviceName: microbot
          servicePort: 80
